version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-puntog}
      POSTGRES_USER: ${POSTGRES_USER:-puntog}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  api-gateway:
    build:
      context: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - redemption-service
      - station-service
      - ad-engine
      - raffle-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

  redemption-service:
    build:
      context: ./services/redemption-service
    container_name: redemption-service
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - QR_SIGNATURE_SECRET=${QR_SIGNATURE_SECRET}

  station-service:
    build:
      context: ./services/station-service
    container_name: station-service
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

  ad-engine:
    build:
      context: ./services/ad-engine
    container_name: ad-engine
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

  raffle-service:
    build:
      context: ./services/raffle-service
    container_name: raffle-service
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

volumes:
  postgres_data:
  redis_data: