version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-puntog}
      POSTGRES_USER: ${POSTGRES_USER:-puntog}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  jaeger: # NUEVO: Para tracing distribuido
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "14268:14268" # API

  debezium-connect: # NUEVO: Para el patrón Outbox
    image: debezium/connect:2.5
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - rabbitmq # Assuming Kafka is not directly in docker-compose, but RabbitMQ is for events
    environment:
      BOOTSTRAP_SERVERS: 'kafka:9092' # Placeholder, assuming Kafka is managed externally or will be added
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
    volumes:
      - ./ops/debezium:/kafka/connect

  api-gateway:
    build:
      context: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - redemption-service
      - station-service
      - ad-engine
      - raffle-service
      - jaeger # NUEVO
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317 # NUEVO

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    depends_on:
      - postgres
      - redis
      - jaeger # NUEVO
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317 # NUEVO

  redemption-service:
    build:
      context: ./services/redemption-service
    container_name: redemption-service
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - jaeger # NUEVO
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - QR_SIGNATURE_SECRET=${QR_SIGNATURE_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/puntog # NUEVO
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317 # NUEVO

  station-service:
    build:
      context: ./services/station-service
    container_name: station-service
    depends_on:
      - postgres
      - jaeger # NUEVO
    environment:
      - POSTGRES_HOST=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317 # NUEVO

  ad-engine:
    build:
      context: ./services/ad-engine
    container_name: ad-engine
    depends_on:
      - postgres
      - jaeger # NUEVO
    environment:
      - POSTGRES_HOST=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317 # NUEVO

  raffle-service:
    build:
      context: ./services/raffle-service
    container_name: raffle-service
    depends_on:
      - postgres
      - jaeger # NUEVO
    environment:
      - POSTGRES_HOST=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317 # NUEVO

volumes:
  postgres_data:
  redis_data: