
server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:puntog}
    username: ${POSTGRES_USER:puntog}
    password: ${POSTGRES_PASSWORD:changeme}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  redis:
    host: ${REDIS_HOST:localhost}

app:
  jwt:
    secret: ${JWT_SECRET}
    refreshSecret: ${JWT_REFRESH_SECRET}
    expirationMs: 900000 # 15 minutes
    refreshExpirationMs: 604800000 # 7 days
  otp:
    provider: ${OTP_PROVIDER:mock}
    length: 6
    expiration-minutes: 5
