
openapi: 3.0.3
info:
  title: Ad Engine (Synapse)
  version: 1.0.0
paths:
  /ad/select:
    post:
      summary: Select an ad based on context
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdSelectionRequest'
      responses:
        '200':
          description: An ad creative to display
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdCreative'

components:
  schemas:
    AdSelectionRequest:
      type: object
      properties:
        user_id:
          type: string
        station_id:
          type: string
        context:
          type: object
    AdCreative:
      type: object
      properties:
        creative_url:
          type: string
        impression_url:
          type: string
        duration_seconds:
          type: integer
