
openapi: 3.0.3
info:
  title: Auth Service
  version: 1.0.0
paths:
  /auth/otp/request:
    post:
      summary: Request an OTP code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtpRequest'
      responses:
        '200':
          description: OTP sent successfully
  /auth/otp/verify:
    post:
      summary: Verify OTP and get tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OtpVerifyRequest'
      responses:
        '200':
          description: Verification successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

components:
  schemas:
    OtpRequest:
      type: object
      properties:
        phone:
          type: string
          example: '+50688888888'
    OtpVerifyRequest:
      type: object
      properties:
        phone:
          type: string
          example: '+50688888888'
        code:
          type: string
          example: '123456'
    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
