name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Build and push Docker images
        # This step would iterate through services and apps, build them,
        # and push to ECR. For brevity, this is a placeholder.
        run: |
          echo "Building and pushing images..."
          # Example for one service:
          # docker build -t ${{ steps.login-ecr.outputs.registry }}/auth-service:${{ github.sha }} ./services/auth-service
          # docker push ${{ steps.login-ecr.outputs.registry }}/auth-service:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install gasolinera-jsm ./infra/helm/gasolinera-jsm \
            --namespace staging \
            --set image.tag=${{ github.sha }} \
            --set image.repository=${{ steps.login-ecr.outputs.registry }}
